### ISSUE TITLE
地図描画関連のメソッドに縮尺と著作権表記を追加する

### ISSUE THREAD

**Issue by ryota-kimura-dtws** [dtws/dsutils#2]
* dtws1 version:
* Python version:3.6.0
* Operating System:mac

### Description

カスタムコンサルでの納品を考慮して、
地図描画関連のメソッド(ヒートマップ関連)に
縮尺と著作権表記を追加する

### What I Did

以下のようにmapの初期化時にcontrol_scaleをTrueにすることで、
左下に縮尺が表示される
```
fmap = folium.Map(・・・省略・・・control_scale = True・・・省略・・・)
```

以下のようにmapを一度初期化した上で、OSMのリンクを貼った
レイヤーをオーバーラップさせることで、著作権表記を追加する
```
#〜foliumのマップ描画〜
fmap = folium.Map(hogehoge)
#〜foliumのマップ描画〜
copyright = ' <a href="https://www.datawise.co.jp/">  | © DATAWISE   </a>,' 
folium.raster_layers.TileLayer(
　　tiles='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
　　name='OpenStreetMap2',
　　attr=copyright,
　　overlay=True).add_to(fmap)
```
####

**Comment by hotoku-dtws** [comment]
@hidaka-dtws ↑はhtml出力だけ言及されてると思うんですが、png出力の方も、できればお願いします。
